### ISSUE TITLE
keys with spaces are not supported?

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#1248]
It seems that it's not possible to pass keys with spaces anymore:

```
$ dune exec -- tutorial/hello-key/main.exe --hello="built with dune"
hello_key: too many arguments, don't know what to do with `with', `dune'
Usage: hello_key [OPTION]...
Try `hello_key --help' for more information.
```

Not sure what is happening, but it's worth investigating.

**Comment by dinosaure** [comment]
Fixed by mirage/mirage-bootvar-unix#2. About Solo5 the execution path is different and it should work (may be @hannesm can confirm that).

**Comment by hannesm** [comment]
The fix by @dinosaure for mirage-bootvar-unix looks like it solves the issue reported for the unix target.

For solo5 (spt & hvt), there'd be some more stuff needed:
- on the commandline, passing `--hello="foo bar baz"` or `--hello=foo\ bar\ baz`
- solo5 hvt tender (in hvt/hvt_boot_info.c setup_cmdline, sees: `argc 1: --hello=foo bar baz` <- here that would need to escape the whitespaces (i.e. `--hello=foo bar baz` -> `--hello=foo\ bar\ baz`)
- then parse_argv (used by Mirage_bootvar_solo5) should be fine to remote the backslashes again

Now, the question is what is happening on virtio / xen / muen (where we're not in control of the tender)? And is it worth it to go down this route? Apart from the simple hello world unikernel, are there actual unikernels where arguments with whitespaces are useful (and btw you can always `--hello="foo\ bar\ baz"` -> the shell takes the `"`, but the `\` remains being passed through).

**Comment by samoht** [comment]
No strong opinion - but it's an error that I have seen many beginners hit, and the error message is not helpful. We should at least define what is allowed in these strings and raise a proper error to explain to the user what's happening.

**Comment by patricoferris** [comment]
@pitag-ha and I just hit this problem when building a simple send/recv TCP unikernel (we wanted to send/recv messages provided as command line arguments where `"hello sonja!"` wouldn't work for example) -- happy for mirage not to support spaces but a better error message would indeed be better :))

**Comment by hannesm** [comment]
As an update on this issue: since mirage 4.5.1 such a hint is printed (see https://github.com/mirage/mirage/pull/1535) and there's been a longer history about this topic (from https://github.com/mirage/mirage/pull/1535#issuecomment-2117254946):

- https://github.com/mirage/parse-argv/pull/6
- https://github.com/Solo5/solo5/issues/281
- https://github.com/Solo5/solo5/pull/283
- https://github.com/mirage/mirage-solo5/issues/33
- https://github.com/mirage/mirage-bootvar-unix/pull/2
- https://github.com/mirage/mirage/pull/1535

**Comment by hannesm** [comment]
I'll close this issue, there's a warning emitted. If someone has the requirement for "better support for keys with spaces" that is done uniformly across the backends, please either reopen or create a new issue with the desired design. In the above comment, various approaches have been collected - none got merged due to lack of cross-target uniform semantics (as far as I remember).
