### ISSUE TITLE
Meaning of `Mirage.http`

### ISSUE THREAD

**Issue by reynir** [mirage/mirage#1373]
The `Mirage` module defines `http`, `http_client` and `http_server`. It is a bit unclear from the name what `http` represents, but looking at the implementations it seems it's a http server only. Maybe we can deprecate `http` and use `http_server` going forward?

CC/ @dinosaure who added `http_server`.

**Comment by dinosaure** [comment]
Yes, I did `http_server` (and did not reuse `http`) because the interface that `Paf_mirage.S` provides is different from the one that CoHTTP provides. In other words, the interface that `http` represents is different from the one that `http_server` proposes.

The first thing is that the name `http` is problematic, is it a server? A client? One can infer the former from the existence of `http_client` though.

For my part, my opinion would be to remove `http` and consider `http_client` to represent another interface than the one proposed by CoHTTP. I would even consider prefixing these interface representations with their implementations.

It seems clear that the consensus around HTTP (client and server) and the conflict between Mimic (which still hasn't found consensus) and Conduit is revealed here. I would still like to point out that if both servers are working (Paf & CoHTTP), only one of them is used (Paf for what concerns mirage.io and unipi). Only Paf is able to handle ALPN and H2. As far as the client is concerned, quite a lot of work has been done for opam-mirror.

**Comment by reynir** [comment]
I am closing this issue as my question was answered. We should maybe consider opening another issue for `http` being renamed to something else...?
