### ISSUE TITLE
Testing: packet generation using Ostinato

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#193]
This came up in a conversation with @balrajsingh and @crotsos a few times: I found a nice packet generation tool that we could hook into the various stacks for more testing.

https://code.google.com/p/ostinato/#Documentation

**Comment by yomimono** [comment]
Ostinato is still alive, and it's considerably easier to get arbitrary data into various layers of the stack now than it was when this issue was first filed.  I think the best use of a tool like Ostinato would be crafting packets to then check into the existing `tcpip` test suite, which there's a [call for help with](http://canopy.mirage.io/Projects/test-tcpip) on the Canopy page.
