### ISSUE TITLE
xen: Avoid generating paths in Makefile containing '.opam/...'

### ISSUE THREAD

**Issue by djs55** [mirage/mirage#272]
The Makefile needs to supply the linker script and libraries (libxen.a et al). It would be better to look them up dynamically, since then I could run 'mirage configure' and include the Makefile in a release.

This is the kind of thing I'm thinking of:

https://github.com/djs55/xen-testvm/commit/55a516d89e9550d471685eb547518cc66ff7bf66

**Comment by yomimono** [comment]
Having come across this randomly, I got as far as figuring out where to change `mirage` to implement this:

https://github.com/mirage/mirage/blob/master/lib/mirage.ml#L1461 -ish to get the lib directory, and 
https://github.com/mirage/mirage/blob/master/lib/mirage.ml#L1371 to set the path differently.  But there are a few twists that I don't understand about what the current code is doing (`expand_names` in particular is not clear to me), and so it's probably going to take more time to implement this there than I have at the moment.

**Comment by samoht** [comment]
The `expand_name` function is a trick that I added to make arbitrary META fields support the `@name/file` syntax which works only for archive fields (see http://projects.camlcity.org/projects/dl/findlib-1.6.2/doc/ref-html/r721.html and search for "@name/file"). We use it to resolve the xen C flags, so that we can write relative paths in `-L` invocations.

**Comment by hannesm** [comment]
my intuition about this issue is that Mirage3 has "fixed" this one way or another.  There may now be other issues, though.  #823 tries to get rid of the `.opam` installation requirement (which I still haven't reviewed at all).

I'm closing this since the xen-testvm seems to be a bit bitrot in regards to Mirage3.  Please reopen or resubmit in case there's still a problem.  Both the generated Makefile and the generated opam file do not contain any local information, and can be redistributed (unfortunately, `make build` / `mirage build` still require the mirage tool itself, but all dependencies are dynamically looked up (using `pkg-config`)).
