### ISSUE TITLE
Add HVM booting support to MiniOS

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#313]
This is initially to support HVM in Xen, but eventually to use the same bootloader on KVM and VMWare backends.

@jonludlam had some experimental trees that did this a few years ago -- are they still around Jon?

From @djs55 on mirageos-devel:

> http://arjunsreedharan.org/post/82710718100/kernel-101-lets-write-a-kernel
> http://arjunsreedharan.org/post/99370248137/kernel-201-lets-write-a-kernel-with-keyboard-and

**Comment by yomimono** [comment]
We don't need this for KVM anymore since we can get there via solo5, but support for PV on Xen is decreasing in two contexts where it's convenient to be able to run unikernels: Amazon EC2 (which has only one instance type supporting PV, and that type is `t1.micro`, so deprecated it no longer appears in instance type charts) and QubesOS.  I think it's still worth keeping this on our wishlist.

**Comment by hannesm** [comment]
after talking with @mato, this likely boils down to cleaning up the mirage-xen backend to use the freestanding approach and base on a newer minios (which likely supports hvm these days).

**Comment by mato** [comment]
See #1159 for the new PVH-only Xen stack.
