### ISSUE TITLE
Test infrastructure

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#389]
This issue tracks the current initiatives to improve the testing infrastructure of MirageOS. Hopefully this should lead to code more easily testable, with a better overall quality.
- https://github.com/MagnusS/mirage-vnetif
  
  > Virtual network interface and software switch for Mirage. Provides the module Vnetif which can be used as a replacement for the regular `V1.NETIF` implementation in Xen and Unix. Stacks built using Vnetif are connected to a software switch that allows the stacks to communicate as if they were connected to the same LAN.
- https://github.com/yomimono/mirage-net-pcap
  
  > mirage-net-pcap is a module that satisfies Mirage's `V1.NETWORK` module type. It reads from a pcap file (currently, provided by the Mirage crunch interface) and saves writes to memory.
- https://github.com/mirage/mirage-flow
  
  >  create `V1.FLOW` from various sources

**Comment by samoht** [comment]
@avsm @MagnusS and @yomimono can you comment what are your current plans on this? (just to check that we actually have a plan :p)

**Comment by avsm** [comment]
I want to deploy the OPAM bulk build infrastructure for just the Mirage packages, running in a loop.  It will have output similar to : http://www.recoil.org/~avsm/opam-bulk/

It would be extremely convenient if the Mirage test infrastructure could be structured as a set of OPAM packages that run test cases when installed.  This way we just package them up in an OPAM remote and run them using this infrastructure regularly.

I think that @mor1 and @koleini should also comment on their plans for `mirage-perf`, since those are also excellent unit tests.

**Comment by MagnusS** [comment]
My plan for the vnetif implementation is to make it easier to do automated small scale network tests with unikernels without having to coordinate deployment and network setup. We can also use it to automate tests of the tcp/ip stack, for example with iperf as implemented [here](https://github.com/MagnusS/mirage-vnetif/tree/master/examples/iperf_self).

The implementation supports different backends, so in the longer term the plan is to add support for recording traffic in irmin and to set up more complicated network environments.

**Comment by MagnusS** [comment]
mirage-vnetif is now released in opam and I've added iperf and connect tests that can run in travis to the tcp/ip stack [here](https://github.com/mirage/mirage-tcpip/tree/master/lib_test). It should be possible to write network tests for other libraries in a similar way.

**Comment by hannesm** [comment]
based on mirage-net-pcap and mindy's example unikernels I started (and will hopefully finish soon) a [trace checker](https://github.com/hannesm/trace-checker) which purpose is to read a pcap file, get the (client _and_ server) tcp flow which should be a TLS connection and check its validity... in order to do so I needed to expose slightly more of the tcpip stack (and it's all not yet finished; ideas and pointers to similar projects appreciated)...

**Comment by samoht** [comment]
yay!

**Comment by samoht** [comment]
Ping. Can we have an update on that?

**Comment by yomimono** [comment]
This issue is very fuzzy and somewhat duplicates the more concrete https://github.com/mirage/mirage/issues/584 , so I'm closing it for now.  Feel free to reopen and comment if you think this is premature.
