### ISSUE TITLE
Inter-VM communications via Conduit

### ISSUE THREAD

**Issue by wmhaddad** [mirage/mirage#474]
Submit a request for documentation on "conduit" and how to use it

**Comment by amirmc** [comment]
Thanks for this!  I'll make a related issue on the conduit repo too.

**Comment by dinosaure** [comment]
I will take the opportunity of this issue to clarify the status about Conduit and our eco-system. Currently, we agreed that Conduit becomes less and less useful for our purpose - however, a question remains:

> how to **dynamically** `connect`/instantiate a communication with a _peer_ (an unikernel or something else).

This question becomes difficult because our design is: let the implementer free (from any interfaces) about its implementation and its _signature_ of the `connect` function.

In other words, you can not call `connect` from `Mirage_stack.V4V6`/`Tcpip.Stack.V4V6` - and only the `mirage` tool care at the stage 1 of the compilation about that. A concrete example is about block device and [Solo5 block device][solo5-block] has a difference `connect` than an [Unix block device][unix-block] (and they are semantically different of course). So I talked about block device, TCP/IP stack and so on because it's a **systemic** design which concerns any resources.

Be able, into the application level (inside your `unikernel.ml`), to instantiate something like a connection at the runtime seems difficult so. And this is the purpose of Conduit: be able from a `ctx` to instantiate a connection. This question become required when we want to launch some HTTP requests for example.

However, we saw that Conduit has several limitation (mostly because it's a very old library which was not able to take some advantage from the type-system - and help about abstraction). From our experimentations, we decided to use something else more precise and up-to-date: [`mimic`][mimic]. It wants to do the same job as Conduit but it is more extensible than Conduit and focus on the only ability to `connect`/instantiate/`Mimic.resolve` into the application level.

For the MirageOS perspective, a Mimic context must be filled at the stage 1 of the compilation with protocols (into the `config.ml`). Some _witnesses_ permits the user to fill the context with _certain_ values which are needed to instantiate a "socket" of these protocols. For instance, `ocaml-git` does that:
1) it permits to generate a `ctx` with several protocols: [`tcp`]tcp]/[`ssh`][ssh]/[`http`][http]
2) a `config.ml` [choose](https://github.com/mirage/ocaml-git/blob/4647bcfcc345fd0e076c3a83b76e6c258c7b2854/unikernel/empty-commit/config.ml#L223-L229) these implementations
3) At this stage, we have some [_witnesses_][witnesses] which are bound to some protocols
4) We can fill the given [`ctx` with these witnesses][fill] and their user's values
5) Finally, we can call `Mimic.resolve` with this `ctx` and it will try to instantiate a _certain_ protocol

The ceremony is a bit complex but it permits to instantiate a protocol regardless:
1) the implementation of the protocol
2) the backend chosen by the user
3) according to some arguments which can be define by the implementer

Finally, our initial `connect` is delayed to our `Mimic.resolve` and, by this way, we are able to instantiate a connection to something else like a unikernel _via_ a _certain_ protocol (such as VCHAN for instance as far as it respects our `Mirage_flow.S` interface). Hope that it will help you, the documentation of `mimic` is very useful to play with it step by step and understand the power of the abstraction given by it.

If you think that the documentation is not enough, feel free to create an issue into [`mimic`][mimic] and we will happy to continue to improve it! So, I will close this issue. 

[unix-block]: https://github.com/mirage/mirage-block-unix/blob/283da5977d87fcd5b37572f87028b75c838d8ea0/lib/block.mli#L73-L79
[solo5-block]: https://github.com/mirage/mirage-block-solo5/blob/441606fb0ed812a0ed83edb21ceb12bc3dacf3b6/src/block.mli#L18
[mimic]: https://github.com/dinosaure/mimic
[tcp]: https://github.com/mirage/ocaml-git/blob/4647bcfcc345fd0e076c3a83b76e6c258c7b2854/src/git-mirage/git_mirage_tcp.mli
[ssh]: https://github.com/mirage/ocaml-git/blob/4647bcfcc345fd0e076c3a83b76e6c258c7b2854/src/git-mirage/git_mirage_ssh.mli
[http]: https://github.com/mirage/ocaml-git/blob/master/src/git-mirage/git_mirage_http.mli
[witnesses]: https://github.com/mirage/ocaml-git/blob/4647bcfcc345fd0e076c3a83b76e6c258c7b2854/src/not-so-smart/smart_git_intf.ml#L106-L120
[fill]: https://github.com/mirage/ocaml-git/blob/4647bcfcc345fd0e076c3a83b76e6c258c7b2854/src/not-so-smart/smart_git.ml#L120-L165
