### ISSUE TITLE
Embed crunch in an ELF section rather than static linking

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#489]
Rather than static linking, we could embed the crunch filesystems in an ELF section.  This would:
- speed up compilation time by not passing the block device through ocamlopt
- not require a dynamic block device
- not map the data in memory twice, since it wouldnt be in the code section.

See https://devel.unikernel.org/t/includeos-filesystem-api/108 for the IncludeOS thread on this, so we can obey the same ELF section convention.

**Comment by hannesm** [comment]
There is now https://github.com/dinosaure/caravan which does this (pending mirage integration).

**Comment by hannesm** [comment]
As mentioned above, caravan is about that. I tried this for quite some time, it works in some use cases. I don't think it is a good solution (due to issues in respect with reproducible builds): either pass configuration via command line, or block device, or in a git remote. Also, the ELF section is brittle (since size and where memory is mapped is very dependent on solo5 etc.).
