### ISSUE TITLE
Mirage + ocamlbuild + jsoo.ocamlbuild breakage

### ISSUE THREAD

**Issue by sgrove** [mirage/mirage#503]
`mirage configure` fails with the output seen here https://gist.github.com/sgrove/3ab70913a3fcb27e7a87

Running `make` and then `mirage configure works`, but that seems wrong to me. There looks to be some sort of circular dependency here.

My goal here is to have a 100% reliable, _deterministic_ setup for others to use with this example project. I'm unclear what I'm missing here, or where this would be better addressed.

**Comment by talex5** [comment]
What's in your `config.ml` file? (I don't see it in the gist)

**Comment by dinosaure** [comment]
Unfortunately, this issue become obsolete when we updated our `mirage` tool to use `dune` instead of `ocamlbuild`. From my experiments with `pasteur`, we still have some issues about multi-stage compilation and it seems hard to integrate into the compilation pipe some `js_of_ocaml` results. However, I will close this PR and if the experience was not improve with the `dune` support, feel free to re-open it or open a new one :+1:. Thanks.
