### ISSUE TITLE
IP.write can fail

### ISSUE THREAD

**Issue by talex5** [mirage/mirage#506]
According to https://github.com/mirage/mirage-tcpip/pull/166:

> Calls to `Ipv4.write` and `Ipv4.writev` can fail if a link-level address for the destination IP can't be found via ARP.

This should be either:
- Documented, and the exception exposed in the module type, or
- Turned into an error return

**Comment by talex5** [comment]
(It should almost certainly be an error return, because code calling this will often want to handle network errors e.g. by retrying. I only looked quickly, but I didn't see this being handed in the TCP code; transmitting a TCP segment and getting this error will likely call `async_exception_hook` and exit the unikernel, which is unlikely to be the desired result. Unfortunately, this does mean another API change.)

**Comment by hannesm** [comment]
isn't it `connect` which can fail, but `write` which shouldn't (at least in POSIX).

I'm still undecided and curious what `write` semantics people want, I'd prefer in several scenarios to have an API which allow me to check whether the segment has been acknowledged (certainly in a non-blocking fashion, otherwise bandwidth is poor).

But, in general, a `FLOW.write`(`v`) is a fire and forget operation... (and thus, the TCP/IP implementation should ensure that `write` does not depend on ARP [which should IMHO be cached for a connection])...

**Comment by talex5** [comment]
Note that `IP` isn't a `FLOW`.

I don't think you can cache the next-hop ARP address, because it could easily change during a long-running TCP stream. TCP doesn't have to send every packet in a stream along the same path.

Checking the progress of a segment may be useful, but that's at a different layer (TCP) to this issue (IP).

I think that if the IP code is able to report an error then the API should allow it to do that. If TCP wants to ignore transmission errors and rely on the retransmission logic instead, it can.

**Comment by hannesm** [comment]
oh, sorry for my layer violation. maybe we should talk about the API in more detail in Morocco?

**Comment by talex5** [comment]
Sure :-) Actually, I'd like to discuss lots of things about error handling in Mirage there too...

**Comment by yomimono** [comment]
`IP.write` now returns an error variant, but the specific case mentioned here isn't yet addressed; routing failures still generate an exception rather than a proper error.

**Comment by yomimono** [comment]
Fix merged!
