### ISSUE TITLE
mirage clean doesn't clean up staticN.ml[i]

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#540]
in contrast to #204, I think that the sequence of commands:
```
mirage configure $flags
mirage build
mirage clean
```
should not leave any trace behind

**Comment by mor1** [comment]
As I suggest in #204, I understood `clean` vs `distclean` as (AIUI) a fairly common distinction with the latter removing more than the former -- in this case, generated code files in addition to compiled objects. Regenerating the `staticN.m{l,li}` files can take sufficiently long that avoiding having to do it every time was a reasonably significant time saver on build for websites.

Perhaps if we're not doing so much crunch stuff going forwards though, this is now not such an issue?

(Is there a reason for making this a new issue rather than a comment on the existing issue BTW?)
