### ISSUE TITLE
A way to know the cpu running time of the microkernel

### ISSUE THREAD

**Issue by rixed** [mirage/mirage#638]
I'd like my microkernels to be able to monitor themselves, which requires collecting the CPU time (as in Unix.times but without the breakdown between system/user obviously), so that by comparing this time to the wall clock time I have something similar to the xen cpu %. This may be useful for other purposes as well (although I can't find one on top of my head).

I do not even know if XEN exposes anything like that to the domain, and maybe the only possible implementation is to measure it using hardware registers.

Note: I do not expect this to be considered a critical bug ;)

**Comment by talex5** [comment]
`Sys.time` should give you this.

**Comment by mato** [comment]
You can also get a view of the CPU time used by the unikernel by monitoring it with external tools (e.g. `xl top` for Xen, standard `ps`/`top` on the hypervisor process for KVM, `ps`/`top` on the unikernel process for UNIX).

**Comment by hannesm** [comment]
`Sys.time` wraps `getrusage`, and thus will not be available on Xen/KVM/virtio.  It would be nice to get this information from within the unikernel (instead of from the host), similar to memory usage (where we can use the GC stats).

**Comment by mato** [comment]
@hannesm The underlying layers (Mini-OS, Solo5) would need to have support added for keeping accounts of that information. Not sure it's worth it, given that you can get the information from the host... Having said that, patches welcome!

**Comment by talex5** [comment]
Xen at least provides `times` (for exactly this purpose):

https://github.com/mirage/mirage-platform/blob/14cd4b190373c6d54cdab2241563038e79909a00/xen-posix/src/mini_libc.c#L185

**Comment by dinosaure** [comment]
As far as I can say, we provide a monotonic clock according to the target. That mostly means that we are able to launch a benchmark. You probably should take a look on [`bechamel`][bechamel] which wants to do some micro-benchmark from some metrics. The user is able to add by (him/her)self metrics depending on the target.

But, again, the monotonic clock is available for any targets (we require it for OCaml in anyway). I will close this issue as fixed by the fact that we have an access to such counter.
