### ISSUE TITLE
should the type for interfaces be a numerical index, not a string?

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#645]
See discussion at https://github.com/mirage/mirage/pull/643 .  Currently, the value is a string which some implementations then attempt to interpret as a number, which can be a runtime exception (see https://github.com/mirage/mirage-net-xen/blob/master/lib/frontend.ml#L238 ).

**Comment by hannesm** [comment]
(GitHub tries to be smart... `does not fix xxx` leads to closing `xxx`, thus reopening)

**Comment by yomimono** [comment]
On 12/02/2016 09:04 AM, Hannes Mehnert wrote:

> (GitHub tries to be smart... |does not fix xxx| leads to closing 
> |xxx|, thus reopening)
>
d'oh, thanks, I thought it was smart enough not to do that.

**Comment by dinosaure** [comment]
I will let open this issue but it's no more related to the MirageOS 3 milestone.

**Comment by hannesm** [comment]
I will close this issue. Since we support different backends and multiple network interfaces, using a string for naming is the most cross-platform we can get. Indeed there can be runtime exceptions on backends that assume it is an integer, but the common ground is really a string.

Also, the runtime exception will likely be at boot time, which is fine (much better than at some point during execution).

If you've better ideas about this issue, please re-open with a proposal that covers all supported backends. Thanks a lot (also for your patience)! :)
