### ISSUE TITLE
workflow: provision after build

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#694]
~~~This superseeds https://github.com/mirage/mirage/issues/631 and addresses https://github.com/mirage/mirage/pull/691#issuecomment-261734044~~~

(updated to reflect changes merged via #703)

At the very moment in master:
- `mirage configure` won't call out to opam.  It will configure the unikernel:  generate a main.ml and a Makefile.
- `make depend` will install the missing dependencies
- `make` compiles the OCaml code as before
- crunch is done during build

After XXX, we should be able to do:
- `mirage configure` - same as above
- `make depend` - install forgotten packages
- `make` - compile
- `provision` - link/add secret keys to existing unikernel image.  The build host does not need to be trusted anymore!

There are still some missing pieces (how to actually do the provisioning -- easy with block devices: just provide the device during startup, but unclear how to do crunch here).

I'd be happy to use for MirageOS3 the intermediate solution, but if there are people who have strong ideas and know how to do the rest, we can also target the full provisioning workflow.

**Comment by hannesm** [comment]
now that #703 is merged, I'd leave this open until we have a plan for the provisioning step (esp regarding Crunch to be applied/linked after the unikernel is built)

**Comment by hannesm** [comment]
#204 and #423 are related to this as well.. I guess we'll need a clean proposal how the MirageOS-X (for X > 3.0.0) should work (as mentioned above, I'd hope to have a `configure - build - provision` workflow -- currently the provision happens while building)

**Comment by mato** [comment]
@dinosaure asked me today about implementation approaches for embedding secrets (or any arbitrary data) in a unikernel binary in a separate `provision` step. There are several options:

1. Appending extra data to the binary during `provision` and getting access to a handle to the running binary at run time e.g. (on Linux) via `/proc/self/fd`, then reading this data in OCaml. Unfortunately this won't work across all targets, e.g. at least `virtio`, `muen` and probably also `xen`.
2. We could have `build` produce relocatable objects and do a final link at `provision` time, but I'd stay away from that as it requires having most of the toolchain around for `provision` and would be somewhat fragile.
3. There is a compromise option. If we can live with the requirement that the _maximum_ size of embedded data would _always_ be reserved in a `.data` segment, and this size would be defined at `build` time, then we could essentially reserve a `static char __embedded_data[size];` during `build` and patch the "real" data in at `provision` time. This should work across all targets, since the data will get loaded by "whichever mechanism the target uses to load the binary".

**Comment by hannesm** [comment]
what @mato commented is very reasonable, and his 3rd option would be a reasonable choice (in contrast to previous ideas I had on this topic, I agree to stay away from relocatable objects (for now)).

**Comment by dinosaure** [comment]
> There is a compromise option. If we can live with the requirement that the maximum size of embedded data would always be reserved in a .data segment, and this size would be defined at build time, then we could essentially reserve a static char __embedded_data[size]; during build and patch the "real" data in at provision time. This should work across all targets, since the data will get loaded by "whichever mechanism the target uses to load the binary".

It seems pretty close to what IncludeOS does where they put a new section `.memdisk` just after `.data` and, at the linking time (according configuration), enlarge this section or just put an _empty_ _memdisk_. At the final step, they have a free area in ELF binary generated (so, they don't need to shift anything) where they can _blit_ what they wants.

**Comment by dinosaure** [comment]
Hi @mirage/core !

I finally found a _solution_ for this specific task: https://github.com/dinosaure/caravan

### caravan

`caravan` is a tool which wants to add a new ELF section (after the `.bss` section) and add a new constant into your _unikernel_ (by `functoria`). It wants to follow the process described by @hannesm:

- Make your _unikernel_ with a generated module by `functoria`
  `caravan` comes with a new device which is an OCaml code with a constant: `PROVISION_\000...\000`. This constant contains 16 bytes to be able to store an address and a length. At the beginning, this constant is empty - we can add a test at the beginning of the MirageOS process to see if this constant was properly updated
- Use `caravan` to add a new `.provision` section
  `caravan` is the main tool which takes an ELF executable (not necessary a MirageOS _unikernel_) and follows some steps:
+ fix `.bss` section. `.bss` is a special section which has a length as a loaded section but it does not appear in the file. Because `.bss` is _usually_ the last section of the loaded segment, we need to fix it to have a clean way to afterwords put a new section after the `.bss` section

  It's little bit hard to understand why `.bss` must be fixed into the file but from what I did, just plug a new section after even if we tell the right virtual address (so virtual addr of `.bss` + virtual length of `.bss`), I reached only segmentation fault at the end.

+ add the new `.provision` section. Again, this part is a little bit hard because we need to shift other sections after `.bss` and update the _shstrtab_ (and I assume that this section is at the end of the ELF binary). So, we just copy the given file into the new binary and add the section.

+ At the end, we search `PROVISION` into the binary and properly set values to store virtual address of the `.provision` section and length of it.

From that, we just do a slow `memcpy` from this area to an OCaml value (a `string` or a `bigstring` - for a `bigstring` we can imagine something better than a copy). In a shell:
```sh
$ mirage configure -t unix
$ mirage build
$ caravan -p provision -i filled filled.o
$ ./filled.o
fb1fe706b3845b647e4450208e8e16f34a142afa
```

Examples available in the repository just want to store a SHA1 hash into the binary and print it. Of course, we can imagine something else like a certificate or a serialized KV-store.

### limitation

If you look into the `README.md`, we have several limitations, first we must compile a MirageOS to the UNIX target with `-no-pie` to avoid a wrong virtual address. Secondly, ASLR must be disabled again to have the right virtual address.

### conclusion

It is surely not the last proposition of this task to store in a third step data into an _unikernel_. IncludeOS decided to have a specific link script with a `.memdisk` section which can grow according to a configuration step.

`caravan` wants to go further where only a constant (`PROVISION`) into the binary is needed - we should not be limited by a specific length and we should not be limited by the target chosen by the user - note that I did not test the Xen target.

However, the program is _really_ fragile and I suspect that it will not work on your computer (even if it works on mine and on my server). I tried to find a safe way where steps are really localized and where application of patch wants to be the less invasive as what we can. However, it still is fragile.

But it's a solution and we can start to talk about details, wrong and good ways and finally find the best one for all!

**Comment by hannesm** [comment]
Thanks for caravan. I'm closing this issue since I don't think this is a viable future. Instead, lots of unikernels are built with "configuration via boot parameters" / "configuration in a git remote" -- use the same unikernel image in different setups is the goal I'm following more closely. Any linking hacks are brittle and usually require OCaml tooling on the provisioning side, which is a big dependency as well.
