### ISSUE TITLE
Imposition of `-classic-display`

### ISSUE THREAD

**Issue by mor1** [mirage/mirage#761]
Given there's no way to override `-classic-display` whereas we do have a means for users to inject their own flags via `Makefile.user`, please could we not impose `-classic-display` in the invocation of `ocamlbuild`?

**Comment by hannesm** [comment]
In the meantime (in mirage master), ocamlbuild is not invoked via make anymore.  This is of course a downside, but there is an upside: there is no more too much string concatenation in mirage, and no dependency on make.

While I don't specifically care about `classic-display`, it got added since a large amount of our ecosystem uses it.  If you would like to make something configurable with third-party tools, there may be a generic solution to customise your `ld` and flags, as well as `ocamlbuild` and other tools invoked.  I'd dislike to have another ad-hoc solution such as `warn-error` for all possible `ocamlbuild` command line flags (why is `quiet` not exposed?).

`classic-display` is especially useful in unattended builds to see in the log (console output) what actually happened (such as bulk builds with opam).

just my two cents, feel free to submit a PR removing `classic-display` or making it user-configurable.  IMHO there are more pressing issues than this.

**Comment by avsm** [comment]
Conversely: why do you want to get rid of `-classic-display` @mor1?

**Comment by talex5** [comment]
Don't know about Mort, but I want to get rid of it because it's hard to see real warnings in between all the verbose output about compiler commands.

Also, it's a bit silly having the different layers of our build stack fighting with each other. e.g. the ocamlbuild authors decided to turn this off by default, then some build tool (e.g. topkg) decides to override that and turn it on, then the actual application decides to override it again to disable it, then maybe some user decides to override it again because they want it on in some particular case. It should be set once, under the ultimate control of the user.

**Comment by avsm** [comment]
> Also, it's a bit silly having the different layers of our build stack fighting with each other

Yes, agreed.

**Comment by dbuenzli** [comment]
> because it's hard to see real warnings in between all the verbose output about compiler commands.

A good editor allows you to directly jump to the warning and error locations.

> then some build tool (e.g. topkg) decides to override that and turn it on,

The reason is that this option makes it much easier to debug build problems (there is `_build/log` but it's interspread with much more information I'm usually not interested in).

**Comment by mor1** [comment]
Basically -- what @talex5 said. 

To precis an IRC chat with @hannesm yesterday:
* This isn't fantastically important, but it was the first thing I noticed trying out Mirage3
* There are apparently problems with Travis eating output lines using the "sophisticated" output of `ocamlbuild` hence the desire to default to "classic"
* Reducing the number of things users can (mis-)configure is good, but my view is that tool display options reasonably could be user configurable

So-- if there are observed problems with Travis and sophisticated display then we certainly need to be able to use `-classic-display`, and we won't plumb through all the `ocamlbuild` CLI options to `mirage`. OTOH, it considerably clutters up output for those of us who build locally, and having different tools behave highly opinionatedly about the same thing without consensus seems rather silly.

The conclusion on IRC was that we really need the Mythical Build System :) In the interim, suggestions for sensible workaround welcome. 

@hannesm did suggest those of us who want to turn off `-classic-display` could provide a local shell wrapper to `ocamlbuild` that removes that option. I've had a quick go at that but the combination of ocamlbuild's options and bash parameter quoting is defeating me currently.

**Comment by haesbaert** [comment]
I'm fighting the same issue, I really dislike classic-display.
Actually the colours(always) in _tags made my emacs stop recognizing errors as errors and I couldn't jump to them anymore. This combined with the classic display made me miss some important stuff.

**Comment by haesbaert** [comment]
Well my solution was to hack topkg source and remove all -classic-display, now I'll have to keep a pinned topkg version :/.

**Comment by hannesm** [comment]
fixed by #999 (a `-quiet` is added unless `mirage -v / mirage -vv` is used). if you have further comments on this, it may be worth to open a new issue.
