### ISSUE TITLE
[rfc] Build systems: the Jbuilder/topkg era

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#818]
Jbuilder has now been [released](https://github.com/ocaml/opam-repository/pull/8770) and comes with an excellent [manual](https://github.com/janestreet/jbuilder/blob/master/doc/manual.org) describing how to get started.  It is a compelling new build system that is designed to build batches of libraries together in a fast, developer-friendly fashion.

This issue exists to determine what the ideal template for MirageOS libraries should be, and how we should transition our ecosystem to benefit from Jbuilder's features. We have three tools that dominate the build system used for existing libraries:

- [OASIS](http://oasis.forge.ocamlcore.org): describes and generates the ocamlfind/ocamlbuild runes to build and install libraries and executables.
- [topkg](http://erratique.ch/software/topkg): a DSL for packaging and release workflow (a description of the package generates a `.install` file, and [topkg-care](https://github.com/dbuenzli/topkg) is a CLI to assist with publishing releases.
- [ocamlbuild](https://github.com/ocaml/ocamlbuild): the standard OCaml build system, most often supported by OASIS or topkg with extensions.

Jbuilder is the first tool that deprecates the need for ocamlbuild, and also offers the ability to batch-build a _group_ pf libraries.  So what we need to decide on is the eventual combination of these tools that we would like to use for Mirage releases, and how to implement the missing pieces to ensure that the components work together.  Some notes on this:

- OASIS: we deprecate use of _oasis in new libraries.  This has partially happened in the Mirage3 release process already, but there are still existing libraries using it.
- Jbuilder: there are already PRs coming in ([uri](https://github.com/mirage/ocaml-uri/pull/100), [cohttp](https://github.com/mirage/ocaml-cohttp/pull/533), [qcow](https://github.com/mirage/ocaml-qcow/pull/55), [osx-dnssd](https://github.com/djs55/ocaml-osx-dnssd), [github](https://github.com/mirage/ocaml-github) and [vpnkit](https://github.com/docker/vpnkit/pull/201)) to migrate some of our packages to the new tool, but they do not gel well with topkg (see below).
- topkg: this is currently quite tied to ocamlbuild as a backend, and so would need a connector to Jbuild.  The Jbuild [roadmap](https://github.com/janestreet/jbuilder/blob/master/ROADMAP.org) already notes that topkg integration would be desirable, as that would cover the release workflow implemented by `topkg bistro` today.
- obuild, omake, OCamlMakefile and other build systems: deprecate any use of other build systems in Mirage libraries so we can standardise on jbuilder/topkg.

The end-to-end scenario that is desirable for Mirage is:

- we can clone the full mirage library universe in a single directory, and run a single jbuild invocation to build everything in one place.
- individual libraries can be released upstream using the topkg workflow.
- documentation can be generated locally and [globally](http://docs.mirage.io) using [odig](http://erratique.ch/software/odig) and [odoc](https://github.com/ocaml-doc).
- boilerplate files that are currently checked into individual repos such as .merlin files can all be auto-generated.
- investigate how to have a git monorepo from Mirage so that we can make global changes more easily, and then "slice off" subtrees to submit PRs upstream.  This was an extreme pain point in the Mirage3 release, and it's impractical to continue to pin many repositories for a cross-cutting PR (e.g. https://github.com/mirage/mirage/pull/735)

Please use this issue to give your opinions on any other items I've missed in this discussion!

**Comment by avsm** [comment]
And a useful stat from @djs55 in the https://github.com/mirage/ocaml-qcow/pull/55 PR: build time saw a 4x reduction for just one library, when switched to jbuilder!

**Comment by dbuenzli** [comment]
> topkg: this is currently quite tied to ocamlbuild as a backend

`topkg` is in fact quite build system independent; only `topkg doc` is `ocamlbuild` specific. However I don't really see the point of trying to make both interact. I rather think that `jbuilder` should copy and integrate `topkg` release's worfklow.

I didn't look at `jbuilder` closely but from discussion here and there, it seems to me that it takes again the wrong approach, which is to be `ocaml` specific and anything outside of this realm becomes a pain to perform and integrate.

> boilerplate files that are currently checked into individual repos such as .merlin files can all be auto-generated.

We should rather work to suppress boilerplate files. Most `.merlin` files out there don't need to exist.

**Comment by avsm** [comment]
> topkg is in fact quite build system independent; only topkg doc is ocamlbuild specific.

It's very close to being ocamlbuild-free, but the package description still reference ocamlbuild concepts (e.g. [Pkg.mllib](http://erratique.ch/software/topkg/doc/Topkg.Pkg.html#VALmllib)) fairly often.  

Ideally, I would like to converge on a single library/package description format (either `pkg.ml` or the sexp used in `jbuild`), but using both seem redundant and error prone.   Do you think it's practical to generate a `jbuild` sexp file from topkg, and thus replace ocamlbuild entirely?  This would let us use topkg's excellent release workflow, and Jbuild's ocaml-specific build logic.

**Comment by talex5** [comment]
We tried using jbuilder for various projects at the recent hackathon (mirage-profile, cuekeeper, conduit and 0install). It looked nice, but I didn't manage to get it working on any project. The main issues were due to use of pre-processors (cstruct ppx, js_of_ocaml ppx, camlp4, etc). Sounds like there are plans to fix that. I think it didn't support packfiles either, although I think it may provide a better alternative.

Auto-generating .merlin files would be great, but losing automated releases seems bad. Might be good to start with one of the more difficult projects first (e.g. with C and Xen C libraries, conditional compilation with cppo, etc) to get some confidence it will cope will all our projects.

**Comment by avsm** [comment]
> Might be good to start with one of the more difficult projects first (e.g. with C and Xen C libraries, conditional compilation with cppo, etc) to get some confidence it will cope will all our projects.

Agreed. I'm taking a look at porting [vpnkit](https://github.com/docker/vpnkit), and some of @dsheets' suite of Ctypes bindings.  

Which libraries do you have that still require `-pack` files? Ideally, we should replace those with module aliases.  I just ran across another use of `-pack` in [ocaml-dns](https://github.com/mirage/ocaml-dns) which needs to be ported as well.

**Comment by dbuenzli** [comment]
> still reference ocamlbuild concepts (e.g. Pkg.mllib) fairly often.

Not at all. That's only a shortcut for `ocamlbuild` users to keep their things DRY. I just reads the file and generates install moves for you. The `.mllib` concept doesn't live in `topkg` itself.

> Do you think it's practical to generate a jbuild sexp file from topkg, and thus replace ocamlbuild entirely? This would let us use topkg's excellent release workflow, and Jbuild's ocaml-specific build logic.

This is not the way `topkg` works. In `topkg` you describe install moves and this generates a `.install` file with the moves and a corresponding invocation in your build system so that what is mentioned in the moves will be there when it needs to be installed. 

Again I think it would be much more productive that `jbuilder` provides a `topkg`-like release workflow by itself. However if people want some kind of easier `jbuilder` and `topkg` integration I'll welcome PRs on this but I personally don't have plans to work on that as the benefit/cost ratio of switching to `jbuilder` seems too small for the time being.

**Comment by djs55** [comment]
@talex5 ocaml-qcow uses ppx (`ppx_sexp_lib`) and adding `(preprocess (pps (ppx_sexp_conv)))` to the `jbuild` file seemed to make it work. I'm not a ppx expert though -- is there something different with `cstruct.ppx` do you know?

**Comment by dbuenzli** [comment]
> Again I think it would be much more productive that jbuilder provides a topkg-like release workflow by itself.

Btw. If `jbuilder` people wants to steal some code from `topkg` (e.g. the tar encoder for reproducible tarballs, etc) I'll gladly relicense it under their license.

**Comment by orbitz** [comment]
I have created my own build system called `pds` that can be found here: https://bitbucket.org/mimirops/pds/

It does not depend on ocamlbuild.  It supports parallel builds, has a simple set of semantics, and a build description is machine readable and writable.  It supports building things outside of Ocaml and can either be at the top of the build system or the bottom or somewhere in-between.  It produces makefiles for the actual building with will-defined names that other makefile's can include and target.  The whole system is around 600 lines of Ocaml code and around 400 lines of makefile's.

I haven't tested it on large scale projects, the largest I have is here: https://bitbucket.org/acslab/abb_intf/src/bcbc40cc00a31cc663a15eaef107c97a71a197da/pds.conf?at=dev&fileviewer=file-view-default

Being machine readable, it is the foundation for `hll` which is a tool that takes a `pds.conf` and a `hll.conf` and constructs a opam package (and the same principle can be used to build any kind of package).

`pds` is not awesome but I made it because I found the other tools required learning some config language that was more expressive, or unclear, than I needed to just build a simple system.  I also found building complex things challenging, like something that uses Ctypes in interesting ways, that works fairly well in `pds`.  For example, a small but complicated build are my `kqueue` bindings found here:

https://bitbucket.org/acslab/ocaml-kqueue/src

And the funny Ctype's build process is in this additional Makefile:

https://bitbucket.org/acslab/ocaml-kqueue/src/e9858dacf028921fc651c518259a4919cdd3066e/src/kqueue/kqueue.mk?at=master&fileviewer=file-view-default

The Makefile part could be removed as long as it is replaced with something else that is portable (Blaze, perhaps?).

I don't expect anyone to like it or want to use it but I'm bringing it up here as an alternative.  `pds` targets users who want to toss some files in a directory and make 1 small config, in a fairly well known configuration language, to build the system but can hopefully scale to larger, so if that is a target audience, perhaps it's worth considering.

Sorry for the thread hi-jack!

**Comment by avsm** [comment]
> Sorry for the thread hi-jack!

Not at all -- thank you for bringing pds to our attention!

**Comment by hannesm** [comment]
I agree with @talex5 - if someone wants to adapt jbuilder, please try some difficult packages first -- i.e. those which need C libraries to be compiled for multiple targets (@avsm neither dns nor vpnkit is such a library AFAICS).  Another source of trouble may be testrunners, and tests which optionally depend on other packages (here, dns is a good example).

I'd also appreciate to finish the topkg porting of all our libraries first (to get a unified tool) -- ~~~http://canopy.mirage.io/Projects/topkg~~~ https://github.com/mirage/canopy-data/blob/master/Projects/topkg#L16  contains a list of libraries which need porting (unfortunately, canopy.mirage.io does still not update itself after pushes to its git repository, @avsm could you please fix this!)

I actually don't have any problem pinning 35 packages for a change... changing APIs is hard, but for Mirage3 preparation this was doable.  We overlooked some libraries (due to missing tests/examples/usage in mirage-skeleton, which is tracked in #739), but I doubt that jbuilder will magically solve this.

**Comment by rgrinberg** [comment]
> We tried using jbuilder for various projects at the recent hackathon (mirage-profile, cuekeeper, conduit and 0install). It looked nice, but I didn't manage to get it working on any project. The main issues were due to use of pre-processors (cstruct ppx, js_of_ocaml ppx, camlp4, etc). Sounds like there are plans to fix that. I think it didn't support packfiles either, although I think it may provide a better alternative.

Yeah, it's unfortunate that jbuilder will not support the traditional way of running ppx (through ocamlfind). Which means that we'll have to wait for most ppx extensions to be ported to ocaml-migrate-parsetree to work with it. The current status of this is as follows:

* All of janestreet's ppx's have been transitioned but are yet to be released
* Hhugo is working on js_of_ocaml
* Fred ported ppx_deriving and cstruct.

That leaves only the lwt.ppx as the only commonly used ppx in mirage that hasn't been ported yet.

**Comment by talex5** [comment]
I don't think we use `lwt.ppx` in mirage.

**Comment by avsm** [comment]
Yeah, I'd like to deprecate use of `lwt.ppx` in Mirage libs, as it's often clearer just to write the code out manually.  The advantage of the new scheme is that it's a faster ppx pass as only one binary is generated rather than multiple AST passes.  Note that all the Jane Street ppxs are now released in opam stable.

**Comment by avsm** [comment]
Update: see https://github.com/diml/topkg-jbuilder for a topkg-jbuilder bridge so that builds can happen via jbuilder and the topkg release workflow maintained.

**Comment by avsm** [comment]
As we've been porting to libs to jbuilder, I wanted to try out one of its new features that only comes with having more libraries ported: you can simply drop in a group of separate repositories into a single directory, and call "jbuilder build" at the toplevel directory to build them all in one go without requiring OPAM at all.

This has several benefits: for local development you can make changes across multiple repositories, and still rebuild and test without having to tediously 'opam pin' and 'opam update' all the time.  Once you are ready with your changes, you simply git commit each individual repository as normal, and release with topkg.

I've tried this out on the mirage-device/kv/clock/fs group of repositories with some success. If you want to try it, first you need some to clone the jbuilder ports:

mkdir mybuild
cd mybuild
git clone -b jbuilder git://github.com/avsm/mirage-fs
git clone -b jbuilder git://github.com/avsm/mirage-fs-unix
git clone -b jbuilder git://github.com/avsm/mirage-clock
git clone -b jbuilder git://github.com/avsm/mirage-device
git clone -b jbuilder git://github.com/avsm/mirage-kv
jbuilder build
jbuilder runtest

Once you do this, all the individual libraries build and test in one batch. If you modify any of the individual libraries, they rebuild just the pieces that are needed. You can use external OPAM packages as normal (you will need to install a few too get the above example to work -- an exercise for the reader ).  Tests across repositories can be built and run as well.

I think this feature is pretty incredible -- it's an order of magnitude faster for local development, and the rules are also quite simple.  Mirage-clock-unix requires some review as it has -freestanding variants, so I am not in a rush to merge the Jbuilder PRs, but overall I think this definitely the right direction.  All the META files are autogenerated, and topkg works fine.

**Comment by rgrinberg** [comment]
While this is great news, I don't think it's an alternative to further consolidation of very related, and semi independent repository. Even with jbuilder, the many repos approach still suffers from contributors being able to introduce breaking changes far too easily. Cross cutting refactoring still takes far more effort than it could. And finally, the git histories of all these repositories are still very muddied and don't reflect logical changes across many repositories, let alone being able to revert such changes. 

So while it's a huge step forward, I don't think we're out of the waters yet. Let's move forward!

**Comment by bikalgurung** [comment]
@rgrinberg the current master in `ppx_deriving` is still not working correctly with `jbuilder` as yet. I gave a shot(https://github.com/whitequark/ppx_deriving/pull/135) but it is still encountering several issues. This fork by @diml seems to work correctly - https://github.com/diml/ppx_deriving/tree/v4. However, the branch rolls back @let-def's (Fred's?) `omp` changes.

**Comment by yomimono** [comment]
Some claim to resolution of this issue can be made by the existence of [the Mirage packaging guide](https://mirage.io/wiki/packaging) .
