### ISSUE TITLE
documentation for passing runtime args in Xen via `extra`

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#828]
There's some at https://github.com/mirage/mirage-bootvar-xen , but that is not a very intuitive place for anyone to go looking for it.  Perhaps a "runtime parameters by target" post would be useful.

**Comment by hannesm** [comment]
As time has passed, we're in the lucky situation that boot parameters on xen and qubesos have advanced to a state where we can just use them \o/

**Comment by reynir** [comment]
I think this issue was not so much about mirage being able to handle runtime args, but more about "how to use xl" to pass boot parameters. At least in https://github.com/mirage/mirage-nat/pull/50#discussion_r1750108025 I struggled figuring out what incantation to use.

So! It may very well be that this issue belongs to mirage-www. I don't know.
