### ISSUE TITLE
new conduit library

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#882]
Having a conduit library in MirageOS is useful, as it allows to abstract protocol schemes from the way to handle the connections using these protocols: for instance, we want MirageOS client to connect to `https://foo` and that should just work (provided the TLS support has been compiled in). For MirageOS servers, it is a bit less clear that this is useful, but maybe allowing a server to be configured by listing its external names could be handy (e.g. listen both on `https://foo` and on `http://foo`).

Regardless of its usefulness, today I feel that we still don't have the right interface for `mirage-conduit`. The library is using first-class modules (whereas the rest of the MirageOS world is using normal functors) and `cppo`. It's pretty hard to use and to extend.

Ideally, this library should just provide a basic mechanism to register protocol scheme and client libraries should register themselves. This could use an open type, or whatever fancy mechanism, but the resulting API should be *simple* to use, to extend and understand :-)

Any thoughts?

**Comment by hannesm** [comment]
I still struggle with the intend of conduit: it collects (a) naming services (DNS, translations of services into port number), and (b) transport protocols - TCP and TLS and vchan.

IMHO (a) and (b) should be separated into independent libraries.  good news is that (a) is mainly achieved by ocaml-uri and ocaml-dns atm (I'd appreciate to have a module interface somewhere and hook my udns instead of ocaml-dns in the soon future).
for (b) I don't know enough what your use cases are, there are different properties of protocols (reliability: UDP no, TCP/TLS: yes; stream control; authentication: TCP no, TLS depends).  I'm not convinced the conduit interface reflects this well (or do we not care?), and would likely be more easily convinced if someone would briefly summarise the purpose of mixing `http` and `https` in a single library (does the user care about authentication? how does the server provide secrets?  when is `http` ok to use, when not?), how to deal with errors (connection, authentication problems, expired certificates), and how to provide additional resources (private key and certificate(s)).

**Comment by samoht** [comment]
I agree that the current conduit library is conflating too many things currently. However, it is kind of useful to have a service which resolve an url into a flow that you can read and write into.

Maybe we just need to ensure that the related protocols implement the FLOW interface with custom constructors and errors (as we do in the rest of the stack).

**Comment by hannesm** [comment]
atm the resolver API is embedded in conduit (see  https://github.com/mirage/ocaml-conduit/blob/master/lib/resolver.mli) -- shouldn't we have a mirage-resolver package with this interface (or a revised one!?), which is then used by e.g. the git client, the http client, etc.!?  potential implementations would be the existing ocaml-dns, a udns-based stub resolver, a udns-based recursive resolver, a hardcoded name-resource record list, ... 

what do you think?  should I start with such a module interface?

**Comment by samoht** [comment]
Yea that sounds good; I am wondering if we want non-IP resolver too (like for vchan) but that's probably something that should live in a different resolver library (not sure exactly how this would work though, though).

**Comment by avsm** [comment]
see https://github.com/dinosaure/tuyau for wip by @dinosaure

**Comment by hannesm** [comment]
for a resolver API, there has been some work on [udns](https://github.com/roburio/udns), and esp a [client API](https://github.com/cfcs/udns-client/blob/master/lib/udns_client.mli) (the relevant GADT for DNS resource records is hiding [here](https://github.com/roburio/udns/blob/master/src/dns_map.mli#L21)) //cc @cfcs

**Comment by cfcs** [comment]
I'd like to second @hannesm's suggestion to separate out the DNS-resolver API.
I found it pretty tricky to find a place to hook my code in, and `conduit` comes with some relatively large dependencies that may not be necessary if all I want to do is do DNS lookups: (`ppx_sexp_conv`, `sexplib`, `uri` -- and they pull in `re`, `stringext`, `sexplib0`, `seq`, `base`, `ocaml-migrate-parsetree`, `ppxlib`, `stdio`, `ppx_derivers`, `num`, `parsexp`, ...).

I haven't done enough MirageOS programming to have anything intelligent to say re: `conduit`.

**Comment by hannesm** [comment]
closing this since conduit 3.0 has landed (and mirage support for it is getting to you soon). there is as well a separate DNS client API (part of ocaml-dns) -- and there could be a "Mirage device" for this dns client (next to the resolver, which produces a Conduit_mirage_dns). If there's demand, let's open another issue with a more specific use-case.
