### ISSUE TITLE
How to build with ctypes

### ISSUE THREAD

**Issue by Ulrar** [mirage/mirage#917]
Hi,

I've read [the article](https://mirage.io/blog/modular-foreign-function-bindings) about ctypes / cstubs on the blog, and as I understand it it means we can use C libraries in MirageOS unikernels. The code is easy enough to write, but the article doesn't explain how to build with cstubs, and a lot of googling doesn't help.

Is there any example or doc about building mirage with a C library ? I imagine I have to at least reference the .c and .ml file somewhere in there, maybe in the myocamlbuild.ml, but I'm not sure where or how.
Thanks

**Comment by ichigoXZ** [comment]
There is a [tutorial](https://web.archive.org/web/20130818065407/http://www.linux-nantes.org/~fmonnier/ocaml/ocaml-wrapping-c.php)about wrapping c to ocaml. 

But I don't know how to use it in mirage. Have you solved this yet.

**Comment by dinosaure** [comment]
Hi @Ulrar,

The MirageOS ecosystem has some examples of how to use C stubs and link them with your _unikernel_. The most recent example is [digestif.0.7.4](https://github.com/mirage/digestif.git).

The key is to compile C stubs with specific C flags given by target. In our case:
- Solo5 and `ocaml-freestanding`
- Xen and `mirage-xen-posix`

These flags are available with several ways but the current used for MirageOS is `pkg-config`. Let's take `bigstringaf` which is a small library (smaller than `digestif`) and compatible with MirageOS.3.x. Into the `lib/` directory, you can view two sub-directories:
- `freestanding/` for Solo5
- `xen/` for Xen

These directories want to compile the initial C stubs (they [copy it](https://github.com/inhabitedtype/bigstringaf/blob/master/lib/freestanding/dune#L9)) `bigstringaf_stubs.c` with flags given by a shell-script [`cflags.sh`](https://github.com/inhabitedtype/bigstringaf/blob/master/lib/freestanding/cflags.sh) which does the call to `pkg-config`. Given flags are stored into a file `cflags.sexp` and [used](https://github.com/inhabitedtype/bigstringaf/blob/master/lib/freestanding/dune#L7) by the build-system.

At the end, the package should provide an other `META` (a description of the layout of your libraries understandable by `dune` and other tools like `ocamlbuild`) [to describe](https://github.com/inhabitedtype/bigstringaf/blob/master/META.bigstringaf.template) right static library according the target. But, as you can see, it depends on which build-system you use.

#### The `mirage` tool

Then, the `mirage` tool can collect this information given by the `META` file and link correctly your _unikernel_ with the right static C library according the target.

#### Future

Currently, this _how-to_ works mostly because we currently use `ocamlbuild` to build a _unikernel_ but keep in your mind that this _layout_ will change soon when we have a plan to move to `dune`. Of course, while we prepare the move to `dune`, we will provide a proper _how-to_ (which should not be so different than what I said here).

**Comment by hannesm** [comment]
The future is now, and mirage 4 compilation model allows to integrate any C code that builds with https://github.com/mirage/ocaml-solo5 nolibc. Now a cross-compiler is used, and no need for custom Makefile and cflags.sh anymore \o/ If you still struggle, please open a new issue. Thanks.
