### ISSUE TITLE
Fatal error: exception Dns__Protocol.Dns_resolve_error(_)

### ISSUE THREAD

**Issue by Ulrar** [mirage/mirage#918]
Hi,

I've had a mirage unikernel in production for a few weeks now, but every once in a while it crashes. Since it's a bit hard to keep traces of what happens to it I had no idea why, but I've started a screen to keep the serial output somewhere (if anyone has a good way to do that on KVM ..) and this morning I have the error : 

```
Fatal error: exception Dns__Protocol.Dns_resolve_error(_)
Raised at file "map.ml", line 122, characters 10-25
Called from file "src0/sexp_conv.ml", line 150, characters 10-37
Solo5: solo5_exit() called
Solo5: Halted
```

Since I don't have a map.ml in my project, I assume that's from mirage / solo5. I run this on proxmox, so it's the regular virtio target.
I thought I was catching all exceptions, but clearly not, not sure why or how this one kills it, but I feel like dying because of a DNS resolution error must be a bug ?
thanks

As a bonus question, is there a way to tell solo5 to actually poweroff after this kind of problems ? It seems to keep the machine up even though it's dead, so proxmox never resets it. If it just went down, the HA process would start it again and it wouldn't matter much

**Comment by mato** [comment]
@Ulrar:

I can't comment on the DNS exception itself, but regarding your other questions:

> keep the serial output somewhere (if anyone has a good way to do that on KVM ..)

If you use `solo5-virtio-run`, then you can just pipe the output somewhere. You'd have to adapt it to proxmox, if that is possible.

> As a bonus question, is there a way to tell solo5 to actually poweroff after this kind of problems ?

Unfortunately that's not possible [*] on `virtio` since the only standard way to poweroff a `virtio` VM involves using ACPI, and that would involve adding a large body of support code + other changes just to get the VM to shut down.

I'd recommend considering moving to a `ukvm`-based unikernel in the future, which has none of the above issues.

[*] There is a qemu-specific hack we use in the test scripts, if proxmox is QEMU-based you _might_ be able to get it to work, look at `solo5-virtio-run` and https://github.com/Solo5/solo5/blob/master/kernel/virtio/platform.c#L100.

**Comment by Ulrar** [comment]
```Poke the QEMU "isa-debug-exit" device to "shutdown"```
So if I find how to have that device, it should be able to poweroff the VM itself, as I understand it. Thanks, I'll look into that !

As for the rest, it's not that simple. We use Proxmox because that's what we have, but I doubt solo5-virtio-run would work with it, Proxmox has it's own stuff on top of qemu/kvm.

As for ukvm, if we have enough unikernels some day to justify dedicating machines to it why not, but that's not the case yet. And it'll need a lot of tools around to manage it, albatros looks neat but I barely understand the idea behind it, I can't imagine putting that in production anytime soon. But if there is a way to do high availability with ukvm someday, sure !

**Comment by Ulrar** [comment]
Seems like adding the isa-debug-exit device solves the auto-reboot issue ! Thanks for that.

Still, that DNS exception happens often (probably says a lot about ovh's network ..).

**Comment by mato** [comment]
@Ulrar: Nice to know that works for you.

@mirage/core Can anyone comment on the DNS exception?

**Comment by hannesm** [comment]
sorry for the late reply. In mid-August 2019 the DNS implementation got a major rewrite, and there should be no more resolve exceptions. Could you try with a recent mirage (3.6.0 or the upcoming 3.7.0), and if you end up with an error, please open a new issue. Thanks!
