### ISSUE TITLE
output "what to do next"

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#921]
in our today's meeting, @samoht mentioned that `mirage` doesn't tell you what to do next, which would be nice:
- `mirage configure` --> `now build your unikernel using mirage build (or make/make depend)`
- `mirage build` --> `now run your unikernel using ./solo5-vt ... `

**Comment by dinosaure** [comment]
> The dune port, on the other hand, should be able to build all the different backends from a single build directory since each target will have a different name. This in turn implies that the build rule can run mirage configure for that backend/key combination as a normal dependency. I'm not quite sure how this plays out with functoria keys and the current CLI entry, but I'm sure we can parameterise that nicely too.

It's currently not the case when we still have a 2-stage compilation:
1) the compilation of the `config.exe`
2) call to the `config.exe` to generate files
3) the compilation of the unikernel

I think this issue is more related about `dune` which should allow a _multi-stage_ compilation. Our case can be essentialized to:
```
$ cat >dune <<EOF
> (executable (name a) (modules a))
> 
> (executable (name b) (modules b))
> 
> (rule (target b.ml) (deps a.exe) (action (run ./a.exe)))
> EOF
$ cat >a.ml <<EOF
> let () = print_endline "let () = print_endline \"Hello World!\""
> EOF
$ dune exec ./b.exe
Error: Rule failed to generate the following targets: b.ml
```

Where `a.ml`/`a.exe` is our `config.ml` and `b.exe` is our unikernel.
